language: python
env:
    - PYTHONPATH=$PYTHONPATH:/home/travis/build/fmv1992/data_utilities/data_utilities/
branches:
  only:
    - develop
    - master
python:
    - "3.4"  # oldest python version supported by numpy
    - "3.6"
before_install:
    - sudo apt-get update
    - pip3 install --upgrade numpy matplotlib seaborn pandas unidecode scikit-learn
install:
    # - git clone 'https://github.com/fmv1992/data_utilities'
script:
    - python3 -c "import data_utilities as du; du.test()"
